// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcvvmfdmekdoocrwsfmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdnZtZmRtZWtkb29jcndzZm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxMTk1MzUsImV4cCI6MjA5MjY5NTUzNX0.7LGm-tyb4SJiuymZe37ejuwYZQTrB0EsaCO0l1vdDpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});